### PR TITLE
Update to zig 0.12.0-dev.3653+e45bdc6bd

### PR DESCRIPTION
**Pull request by Cloudef**
This simply uses the `.raw ` fields of `Uri.Component`, might not be correct in all cases but should be equal to current implementation

### CODE REVIEW

**Comment by melonedo** [comment]
Is this a workaround or just migrating zig's new changes? I would prefer copying zig's implementation for it is easy to maintain.

**Comment by Cloudef** [comment]
Simply migration. By copying do you mean https://github.com/ziglang/zig/blob/master/lib/std/http/Client.zig can be simply copied over?

**Comment by melonedo** [comment]
Of course it is needed to make a few modifications to import TlsClient instead of std.tls.Client.
Also, thank you for updating it! I will merge it after I check it locally.



---Original---
From: "Jari ***@***.***&gt;
Date: Tue, Apr 16, 2024 13:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [melonedo/zig-tls12] Update to zig 0.12.0-dev.3653+e45bdc6bd (PR#7)




 
Simply migration. By copying do you mean https://github.com/ziglang/zig/blob/master/lib/std/http/Client.zig can be simply copied over?

**Comment by Cloudef** [comment]
Okay, then let me do this properly and copy over the latest http client

**Comment by Cloudef** [comment]
Maybe I did it correctly. The upstream TLSClient seems to have some new errors that aren't in your implementation, so I removed those from the switch.

**Comment by melonedo** [comment]
Many thanks!

**Pull request merged**
